server:
  registerDefaultExceptionMappers: false
  rootPath: /v1/*

swagger:
  resourcePackage: io.minebox.resource

# Logging settings.
logging:
  level: INFO
  loggers:
    io.minebox: DEBUG
    io.minebox.nbd.NbdStatsReporter: INFO
    org.bitcoin.Secp256k1Context: ERROR

#netty-spectific settings of minebd
minebd:
  nbdPort : 10811
  maxOpenFiles : 1
  parentDir : minedbDat #for dev this is a relative directory to where it was started in. VM/physical should configure absolute path
  reportedSize : 10G
  encryptionKeyPath: ./localetc/minebox/minebox.key
  authFile: ./localetc/minebox/local-auth.key
  bucketSize : 40M
  httpMetadata: https://metadata.minebox.io/v1/
  ignoreMissingPaths: true
