server:
  registerDefaultExceptionMappers: false
  rootPath: /v1/*

swagger:
  resourcePackage: io.minebox.resource

# Logging settings.
logging:
  level: INFO
  loggers:
    io.minebox: DEBUG
    io.minebox.nbd.NbdStatsReporter: INFO
    org.bitcoin.Secp256k1Context: ERROR
#    io.minebox.nbd.TransmissionPhase: INFO

#netty-spectific settings of minebd
minebd:
  nbdPort : 10809
  maxOpenFiles : 20
  parentDir : /mnt/lower1/data/
  reportedSize : 1TB
  encryptionKeyPath: /etc/minebox/minebox.key
  authFile: /etc/minebox/local-auth.key
  bucketSize : 40M
  httpMetadata: "https://metadata.minebox.io/v1/"
  ignoreMissingPaths: true
