server:
  registerDefaultExceptionMappers: false
  rootPath: /v1/*

swagger:
  resourcePackage: io.minebox.resource

# Logging settings.
logging:
  level: INFO
  loggers:
    io.minebox: DEBUG
    io.minebox.nbd.NbdStatsReporter: INFO

#netty-spectific settings of minebd
minebd:
  nbdPort : 10811
  maxOpenFiles : 1
  parentDir : minedbDat #for dev this is a relative directory to where it was started in. VM/physical should configure absolute path
  reportedSize : 10G
  encryptionSeed: /etc/minebox/minebox.key
  authFile: /etc/minebox/local-auth.key
  bucketSize : 40M
  httpMetadata: "http://localhost:8050/v1/file/"
  ignoreMissingPaths: true
