server:
  registerDefaultExceptionMappers: false
  rootPath: /v1/*

swagger:
  resourcePackage: io.minebox.resource

# Logging settings.
logging:
  level: INFO
  loggers:
    io.minebox: DEBUG
    io.minebox.nbd.NbdStatsReporter: INFO

#netty-spectific settings of minebd
minebd:
  nbdPort : 10809
  maxOpenFiles : 20
  parentDir : /mnt/lower1/data/
  reportedSize : 10G
  encryptionKeyPath: /etc/minebox/minebox.key
  authFile: /etc/minebox/local-auth.key
  bucketSize : 40M
  httpMetadata: "http://localhost:8050/v1/file/"
  ignoreMissingPaths: true
